### ISSUE TITLE
Should demo/clone apps be included?

### ISSUE THREAD

**Issue by longsangstan** [jeromedalbert/real-world-react#4]
Hi,

I really like the concept of having a curated list of open source production react projects (in fact I have made [one](https://github.com/longsangstan/react-open-source-production-apps) myself).

I am just thinking maybe apps like **dribble-demo**, **react-yelp-clone**... should not be included? They are good projects for learning purpose but they are not real world production projects, and they are already in other awesome react list.

My suggestion is that this list should only be focused on projects like **reddit mobile** or **wp-calypso**.

Just my two cents:)

**Comment by jeromedalbert** [comment]
Hey! Thanks for the list, I've added Serverless Website. Maybe I should create a real-world-react-native at some point, but I have no immediate need for it right now.

Anyways, yeah my definition of a real world app was a bit lax initially, in order to have a minimum amount of projects.

Technically speaking, dribble-demo and react-yelp-clone are "production projects" in that they are respectively accessible via http://112.74.28.115:3000 and http://fullstackio.github.io/yelp-clone. But I tend to agree with you, my general feeling for these apps is that they are not "real" enough, although it's hard to quantify exactly.

I guess there is a fine line between what constitutes a "real world" app or not. For example, I accepted the [guyellis/plant](https://github.com/guyellis/plant) project: although it has only 2 stars and probably has low traffic, the **guyellis** seems to be using it for his own needs. And it has real data (cf https://plaaant.com/location/guy-ellis-yard/5851d7d52967c2153ab6c856 and click one of the links, and you can see that the amount of production data he has gathered is quite impressive). This looks "real world" enough to me.

### [TODO] List of projects that may not be "real world" enough:

- [ ] [conduit, aka react-redux-realworld-example-app](https://github.com/gothinkster/react-redux-realworld-example-app). Consistent data every day (although mostly gibberish), has ~ 1000 stars.
- [] [dribble-demo](https://github.com/afghl/dribble-demo)
- [] [github-battle-app, aka react-fundamentals](https://github.com/ReactTraining/react-fundamentals/tree/hosting). Has some data, has 2100+ stars.
- [] [i-have-to-return-some-videotapes](https://github.com/stevenhauser/i-have-to-return-some-videotapes). 65 stars. May qualify as a real world app for its originality and the code being "complex enough".
- [] [invoice-frontend](https://github.com/koodilehto/invoice-frontend). Small project, has 29 stars. May qualify as a real world app because invoicing sounds "corporate", and there aren't a lot of corporate-like apps around.
- [] [lifequote](https://github.com/insin/lifequote). Same, sounds corporate enough.
- [] [mortgage](https://github.com/paulhoughton/mortgage). Same, sounds corporate enough.
- [] [react-photo-feed](https://github.com/lkazberova/react-photo-feed). 54 stars.
I think I'll eventually remove some or all of them, as people submit more and more real world projects. What do you guys think about this list? Should I keep some of them? Or add more?
- [] [react-yelp-clone](https://github.com/fullstackreact/react-yelp-clone). 650 stars. Seems to only works for a small part of San Francisco.

**Comment by jeromedalbert** [comment]
What do you guys think of this list? Which ones should go, which ones should stay?

**Comment by jeromedalbert** [comment]
What do you think @longsangstan ? Which ones should go, which ones should stay? Other opinions welcome.

**Comment by longsangstan** [comment]
@jeromedalbert I agree the definition of "real world" is very subjective.

For me, I would translate "real world apps" into "apps that are used by people in the real world".
So ideally the projects in this list should have a significant amount of real users (~500?).

Projects like reddit-mobile or wp-calypso can easily pass the mark.
The demos/clones should be screened out as there is probably few people are using them.

For the plant app you mentioned.... it's really hard. I would probably not include that for now although it looks like a really cool project with real purpose.

**Comment by jasanst** [comment]
Number of real users seems like the worst possible metric for this list, I'm interested in learning from the code not the business model.  The list you're describing probably belongs elsewhere.

Factors for me are that the libraries used are reasonably up-to-date with a working demo site, that the code actually compiles as expected and it's files/directories are structured, tests are a big bonus as would be authentication.

I think the current selection is pretty good and can be improved over time, the only thing I'd like is maybe a table format summary, highlighting which of the requirements each projects has - making it easy to find for example a redux based project with tests and authentication.

**Comment by longsangstan** [comment]
@jasanst Funny we have the exact opposite view haha.

I think if you are looking for well structured projects to learn from you should probably be looking at list such as [awesome-react](https://github.com/enaqx/awesome-react#react-projects) and [amazing-react-projects](https://github.com/jiwonbest/amazing-react-projects).

To me the most important criteria for this list is that the projects are being used by real people, hence "real world react". I will take a real production app with messy codebase over a well written demo app all day long, for this list.

**Comment by jasanst** [comment]
Obviously @jeromedalbert can build this list however he likes, just as other people can build their own lists.

Maybe our interests are different but I use open source to learn, learning that a commercial application has messy code isn't that useful to me.

I'm looking for a curated list of quality codebases to learn from, real world to me means that you strip out the components and abandoned projects that dominate awesome-react style lists and show practical complete maintained projects.

**Comment by jeromedalbert** [comment]
Thanks for your input @jasanst , I tend to agree with you.

To get a list of projects using redux, you can do `ag 'react-redux' -G 'package.json' -l`. I have added a code analysis section in the README.

**Comment by jeromedalbert** [comment]
After double-checking the projects, I have decided to keep all of them, even react-yelp-clone and dribble-demo, because their codebase is big enough to me. It is also nice to balance huge projects with smaller (but still "real enough") ones, to get a good overall overview and diversity when doing code and libs analysis (via grep, ag, etc).

Smaller and newer projects tend to use the latest bells and whistles, while bigger older ones may be lagging a bit behind, but have more structure. An overview of both is good for analysis and learning purposes.
